In [1]:
import numpy as np

In [4]:
a = np.arange(6)
print(a)
    

[0 1 2 3 4 5]


In [24]:
a.dtype

dtype('int32')

In [9]:
a2 = a[np.newaxis, :]
print(a2)

[[0 1 2 3 4 5]]


In [11]:
a2.shape

(1, 6)

In [15]:
ones = np.ones((2,4))

In [16]:
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
ones.dtype

dtype('float64')

In [26]:
full = np.full((3,4) , 100.)

In [27]:
full

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [29]:
type(full)

numpy.ndarray

In [28]:
full.dtype

dtype('float64')

In [30]:
full.ndim

2

In [33]:
len(full[0])

4

In [34]:
np.size(full)

12

In [22]:
iden = np.eye(2)

In [23]:
iden

array([[1., 0.],
       [0., 1.]])